[package]
name = "libcl-hook"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "cl_hook"

[dependencies]
lazy_static = "1.5.0"
libc = "0.2.172"
libcl-hook-macros = { path = "../libcl-hook-macros" }
