//! A parser for an experimental query language protopyte (ToyQL)

/* Builtins */
WHITESPACE = _{ " " }

/* Characer Rules */
quote      = _{ "\"" }
regex_ctrl = _{ "." | "+" | "*" | "?" | "^" | "$" | "(" | ")" | "[" | "]" | "{" | "}" | "|" | "\\" }
char       = _{ !(regex_ctrl | quote) ~ (LETTER | NUMBER | PUNCTUATION | SYMBOL) }
idchar     = _{ 'A'..'Z' | 'a'..'z' | '0'..'9' | "-" | "_" | "." }
boolop     =  { "|" | "&" }
disjunc    =  { "|" }
neg        =  { "!" }

/* String Rules */
regex = @{ quote ~ (regex_ctrl | char)+ ~ quote }
str   = @{ quote ~ char+ ~ quote }
ident = @{ idchar+ }

/// Common search string type representing simple strings or regular expressions.
/// This can be handled in the parser to allow for optimized matching later.
searchstr = _{ str | regex }

/* Matching Constraints */

/// Constraint atom, i.e. a single matching operation on a variable, either as a single atom or a nested (parenthesized) constraint
atom = { neg? ~ (ident ~ "=")? ~ searchstr }

/// Convenience rule for all subconstraints
subconstraint = _{ atom | neg? ~ "(" ~ constraint ~ ")" }
/// Top-level constraint, consisting of a sequence of atoms joined by boolean operations
constraint = { subconstraint ~ (boolop ~ subconstraint)* }

/* Token-Level Expressions */

/// Token-level quantifiers, i.e. bounded repetition (count), unbounded repetition, optionality
quantifier = { "?" | "+" | "*" | "{" ~ ASCII_DIGIT? ~ ("," ~ ASCII_DIGIT?)? ~ "}" }

/// Raw token or nested (parenthesized) expression
token = { atom | "[" ~ constraint? ~ "]" }

/// Convenience rule for all valid subexpressions
subexpression = _{ (token | "(" ~ expression ~ ")") ~ quantifier? }
/// Token Expression, i.e. a sequence of tokens in the corpus.
/// A series of tokens is connected either implicitly via concatenation or explicitly via disjunction
expression = { subexpression ~ (disjunc? ~ subexpression)* }

/* Parent Rule */

/// The top-level input line
query = { SOI ~ expression ~ EOI }
